image: Visual Studio 2019

version: 0.3.0+{build}

environment:
  DEBUG: 'procmonrest'
  matrix:
    - node_version: '14'
    - node_version: '12'
    - node_version: '10'

matrix:
  fast_finish: true

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:node_version

before_test:
  - npm --version
  - npm install

test_script:
  - npm run appveyor
  - pwsh: |
        $webClient = New-Object System.Net.WebClient
        $webClient.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test-results.xml))

build: off
